<?php
/**
 * Created by PhpStorm.
 * User: lishenyang
 * Date: 2019-10-02
 * Time: 21:43
 */

namespace App\HttpController\Api\V1;


use App\Bean\CourtBean;
use App\HttpController\Base;
use App\Model\CourtModel;
use App\Utility\Pool\MysqlPool;
use App\Utility\Pool\RedisPool;
use App\Validate\CourtValidate;

class Court extends Base
{
    public function index()
    {
        parent::index(); // TODO: Change the autogenerated stub
    }


    public function getList()
    {
        $token = $this->request()->getHeader('token');
        $where = [];
        if( $token[0] )
        {
            $user = $this->checkAuth();
            $where['user_id'] = $user['id'];
        }
        $model = new CourtModel(MysqlPool::defer());
        $list = $model->findAll($where);

        return $this->returnJson('ok' , [
            'list' => $list,
            'total' => $model->getDb()->getTotalCount()
        ]);
    }


    public function create()
    {
        $user = $this->checkAuth();
        $params = $this->request()->getParsedBody();
        (new CourtValidate())->goCheck($params);  //验证数据合法
        $courtBean = new CourtBean($params);
        $courtBean->setUserId($user['id']);
        $result = $courtBean->add();
        if( $result !== false )
        {
            return $this->returnJson('发布成功,感谢您');
        }else{
            return $this->returnJson('系统出错了');
        }

    }
}
